DATA_DIR = "data/asl_mnist"
TRAIN_CSV = f"{DATA_DIR}/sign_mnist_train.csv"
TEST_CSV = f"{DATA_DIR}/sign_mnist_test.csv"

DEFAULT_SEED = 42
DEFAULT_BATCH_SIZE = 64
DEFAULT_NUM_WORKERS = 0
DEFAULT_DEVICE = "auto"

IMAGE_SIZE = 28
INPUT_SIZE = IMAGE_SIZE * IMAGE_SIZE
NUM_CLASSES = 24
DEFAULT_HIDDEN_SIZE = 256
DEFAULT_DROPOUT = 0.5
DEFAULT_EPOCHS = 4
